insert into state (stateName,code) values ('Alabama',1);
insert into state (stateName,code) values ('Arizona',2);
insert into state (stateName,code) values ('Arkansas',3);
insert into state (stateName,code) values ('California',4);
insert into state (stateName,code) values ('Colorado',5);
insert into state (stateName,code) values ('Connecticut',6);
insert into state (stateName,code) values ('Delaware',7);
insert into state (stateName,code) values ('Florida',8);
insert into state (stateName,code) values ('Georgia',9);
insert into state (stateName,code) values ('Idaho',10);
insert into state (stateName,code) values ('Illinois',11);
insert into state (stateName,code) values ('Indiana',12);
insert into state (stateName,code) values ('Iowa',13);
insert into state (stateName,code) values ('Kansas',14);
insert into state (stateName,code) values ('Kentucky',15);
insert into state (stateName,code) values ('Louisiana',16);
insert into state (stateName,code) values ('Maine',17);
insert into state (stateName,code) values ('Maryland',18);
insert into state (stateName,code) values ('Massachusetts',19);
insert into state (stateName,code) values ('Michigan',20);
insert into state (stateName,code) values ('Minnesota',21);
insert into state (stateName,code) values ('Mississippi',22);
insert into state (stateName,code) values ('Missouri',23);
insert into state (stateName,code) values ('Montana',24);
insert into state (stateName,code) values ('Nebraska',25);
insert into state (stateName,code) values ('Nevada',26);
insert into state (stateName,code) values ('New Hampshire',27);
insert into state (stateName,code) values ('New Jersey',28);
insert into state (stateName,code) values ('New Mexico',29);
insert into state (stateName,code) values ('New York',30);
insert into state (stateName,code) values ('North Carolina',31);
insert into state (stateName,code) values ('North Dakota',32);
insert into state (stateName,code) values ('Ohio',33);
insert into state (stateName,code) values ('Oklahoma',34);
insert into state (stateName,code) values ('Oregon',35);
insert into state (stateName,code) values ('Pennsylvania',36);
insert into state (stateName,code) values ('Rhode Island',37);
insert into state (stateName,code) values ('South Carolina',38);
insert into state (stateName,code) values ('South Dakota',39);
insert into state (stateName,code) values ('Tennessee',40);
insert into state (stateName,code) values ('Texas',41);
insert into state (stateName,code) values ('Utah',42);
insert into state (stateName,code) values ('Vermont',43);
insert into state (stateName,code) values ('Virginia',44);
insert into state (stateName,code) values ('Washington',45);
insert into state (stateName,code) values ('West Virginia',46);
insert into state (stateName,code) values ('Wisconsin',47);
insert into state (stateName,code) values ('Wyoming',48);
insert into state (stateName,code) values ('Northeast Region',101);
insert into state (stateName,code) values ('East North Central Region',102);
insert into state (stateName,code) values ('Central Region',103);
insert into state (stateName,code) values ('Southeast Region',104);
insert into state (stateName,code) values ('West North Central Region',105);
insert into state (stateName,code) values ('South Region',106);
insert into state (stateName,code) values ('Southwest Region',107);
insert into state (stateName,code) values ('Northwest Region',108);
insert into state (stateName,code) values ('West Region',109);
insert into state (stateName,code) values ('National',110);

